<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="OPT-LTP-048" failures="1" tests="5" name="personal loan" time="0.076" errors="0" timestamp="2021-01-31T21:00:37 IST">
  <testcase classname="test.Basics1" name="Demo" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Basics1.Demo(Basics1.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.Basics2" name="ploan" time="0.001"/>
  <testcase classname="test.Basics4" name="LoginApihomeLoan" time="0.004"/>
  <testcase classname="test.Basics4" name="MobileloginhomeLoan" time="0.002"/>
  <testcase classname="test.Basics4" name="WebloginhomeLoan" time="0.002"/>
  <testcase classname="test.Basics1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- personal loan -->
